src/Entity/Examen.php
<?php

namespace App\Entity;

use App\Repository\ExamenRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExamenRepository::class)]
class Examen
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $ano = null;

    #[ORM\Column]
    private ?int $periodo = null;

    #[ORM\Column]
    private ?int $mes = null;

    #[ORM\Column(length: 128)]
    private ?string $nombre_legible = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAno(): ?int
    {
        return $this->ano;
    }

    public function setAno(int $ano): static
    {
        $this->ano = $ano;

        return $this;
    }

    public function getPeriodo(): ?int
    {
        return $this->periodo;
    }

    public function setPeriodo(int $periodo): static
    {
        $this->periodo = $periodo;

        return $this;
    }

    public function getMes(): ?int
    {
        return $this->mes;
    }

    public function setMes(int $mes): static
    {
        $this->mes = $mes;

        return $this;
    }

    public function getNombreLegible(): ?string
    {
        return $this->nombre_legible;
    }

    public function setNombreLegible(string $nombre_legible): static
    {
        $this->nombre_legible = $nombre_legible;

        return $this;
    }
}

src/Form/ExamenType.php
<?php

namespace App\Form;

use App\Entity\Examen;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExamenType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ano')
            ->add('periodo')
            ->add('mes')
            ->add('nombre_legible')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Examen::class,
        ]);
    }
}

src/Controller/ExamenController.php
<?php

namespace App\Controller;

use App\Entity\Examen;
use App\Form\ExamenType;
use App\Repository\ExamenRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/examen')]
final class ExamenController extends AbstractController
{
    #[Route(name: 'app_examen_index', methods: ['GET'])]
    public function index(ExamenRepository $examenRepository): Response
    {
        return $this->render('examen/index.html.twig', [
            'examens' => $examenRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_examen_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $examan = new Examen();
        $form = $this->createForm(ExamenType::class, $examan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($examan);
            $entityManager->flush();

            return $this->redirectToRoute('app_examen_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('examen/new.html.twig', [
            'examan' => $examan,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_examen_show', methods: ['GET'])]
    public function show(Examen $examan): Response
    {
        return $this->render('examen/show.html.twig', [
            'examan' => $examan,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_examen_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Examen $examan, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ExamenType::class, $examan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_examen_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('examen/edit.html.twig', [
            'examan' => $examan,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_examen_delete', methods: ['POST'])]
    public function delete(Request $request, Examen $examan, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$examan->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($examan);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_examen_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/examen/_delete_form.html.twig
<form method="post" action="{{ path('app_examen_delete', {'id': examan.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ examan.id) }}">
    <button class="btn">Delete</button>
</form>

templates/examen/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Examen{% endblock %}

{% block body %}
    <h1>Edit Examen</h1>

    {{ include('examen/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_examen_index') }}">back to list</a>

    {{ include('examen/_delete_form.html.twig') }}
{% endblock %}

templates/examen/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Examen index{% endblock %}

{% block body %}
    <h1>Examen index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ano</th>
                <th>Periodo</th>
                <th>Mes</th>
                <th>Nombre_legible</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for examan in examens %}
            <tr>
                <td>{{ examan.id }}</td>
                <td>{{ examan.ano }}</td>
                <td>{{ examan.periodo }}</td>
                <td>{{ examan.mes }}</td>
                <td>{{ examan.nombreLegible }}</td>
                <td>
                    <a href="{{ path('app_examen_show', {'id': examan.id}) }}">show</a>
                    <a href="{{ path('app_examen_edit', {'id': examan.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_examen_new') }}">Create new</a>
{% endblock %}

templates/examen/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Examen{% endblock %}

{% block body %}
    <h1>Create new Examen</h1>

    {{ include('examen/_form.html.twig') }}

    <a href="{{ path('app_examen_index') }}">back to list</a>
{% endblock %}

templates/examen/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Examen{% endblock %}

{% block body %}
    <h1>Examen</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ examan.id }}</td>
            </tr>
            <tr>
                <th>Ano</th>
                <td>{{ examan.ano }}</td>
            </tr>
            <tr>
                <th>Periodo</th>
                <td>{{ examan.periodo }}</td>
            </tr>
            <tr>
                <th>Mes</th>
                <td>{{ examan.mes }}</td>
            </tr>
            <tr>
                <th>Nombre_legible</th>
                <td>{{ examan.nombreLegible }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_examen_index') }}">back to list</a>

    <a href="{{ path('app_examen_edit', {'id': examan.id}) }}">edit</a>

    {{ include('examen/_delete_form.html.twig') }}
{% endblock %}