src/Entity/Alumno.php
<?php

namespace App\Entity;

use App\Repository\AlumnoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlumnoRepository::class)]
class Alumno
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $nro_alumno = null;

    #[ORM\Column(nullable: true)]
    private ?int $programa = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getNroAlumno(): ?int
    {
        return $this->nro_alumno;
    }

    public function setNroAlumno(int $nro_alumno): static
    {
        $this->nro_alumno = $nro_alumno;

        return $this;
    }

    public function getPrograma(): ?int
    {
        return $this->programa;
    }

    public function setPrograma(?int $programa): static
    {
        $this->programa = $programa;

        return $this;
    }
}

src/Form/AlumnoType.php
<?php

namespace App\Form;

use App\Entity\Alumno;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlumnoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('nro_alumno')
            ->add('programa')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Alumno::class,
        ]);
    }
}

src/Controller/AlumnoController.php
<?php

namespace App\Controller;

use App\Entity\Alumno;
use App\Form\AlumnoType;
use App\Repository\AlumnoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/alumno')]
final class AlumnoController extends AbstractController
{
    #[Route(name: 'app_alumno_index', methods: ['GET'])]
    public function index(AlumnoRepository $alumnoRepository): Response
    {
        return $this->render('alumno/index.html.twig', [
            'alumnos' => $alumnoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_alumno_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $alumno = new Alumno();
        $form = $this->createForm(AlumnoType::class, $alumno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($alumno);
            $entityManager->flush();

            return $this->redirectToRoute('app_alumno_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('alumno/new.html.twig', [
            'alumno' => $alumno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_alumno_show', methods: ['GET'])]
    public function show(Alumno $alumno): Response
    {
        return $this->render('alumno/show.html.twig', [
            'alumno' => $alumno,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_alumno_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Alumno $alumno, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AlumnoType::class, $alumno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_alumno_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('alumno/edit.html.twig', [
            'alumno' => $alumno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_alumno_delete', methods: ['POST'])]
    public function delete(Request $request, Alumno $alumno, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$alumno->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($alumno);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_alumno_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/alumno/_delete_form.html.twig
<form method="post" action="{{ path('app_alumno_delete', {'id': alumno.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ alumno.id) }}">
    <button class="btn">Delete</button>
</form>

templates/alumno/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Alumno{% endblock %}

{% block body %}
    <h1>Edit Alumno</h1>

    {{ include('alumno/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_alumno_index') }}">back to list</a>

    {{ include('alumno/_delete_form.html.twig') }}
{% endblock %}

templates/alumno/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Alumno index{% endblock %}

{% block body %}
    <h1>Alumno index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Nro_alumno</th>
                <th>Programa</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for alumno in alumnos %}
            <tr>
                <td>{{ alumno.id }}</td>
                <td>{{ alumno.name }}</td>
                <td>{{ alumno.nroAlumno }}</td>
                <td>{{ alumno.programa }}</td>
                <td>
                    <a href="{{ path('app_alumno_show', {'id': alumno.id}) }}">show</a>
                    <a href="{{ path('app_alumno_edit', {'id': alumno.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_alumno_new') }}">Create new</a>
{% endblock %}

templates/alumno/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Alumno{% endblock %}

{% block body %}
    <h1>Create new Alumno</h1>

    {{ include('alumno/_form.html.twig') }}

    <a href="{{ path('app_alumno_index') }}">back to list</a>
{% endblock %}

templates/alumno/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Alumno{% endblock %}

{% block body %}
    <h1>Alumno</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ alumno.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ alumno.name }}</td>
            </tr>
            <tr>
                <th>Nro_alumno</th>
                <td>{{ alumno.nroAlumno }}</td>
            </tr>
            <tr>
                <th>Programa</th>
                <td>{{ alumno.programa }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_alumno_index') }}">back to list</a>

    <a href="{{ path('app_alumno_edit', {'id': alumno.id}) }}">edit</a>

    {{ include('alumno/_delete_form.html.twig') }}
{% endblock %}